---
- name: Configure Docker on Deployserver
  hosts: deployserver   # Ensure this matches your inventory file
  become: true
  tasks:

  - name: Update apt package index
    apt:
      update_cache: yes

  - name: Install required system packages
    apt:
      name:
        - python3-pip
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: present

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Start and enable Docker service
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Add user to Docker group
    user:
      name: ubuntu
      groups: docker
      append: yes

  - name: Install Docker SDK for Python
    pip:
      name: docker

  - name: Pull Docker image from DockerHub
    docker_image:
      name: sapteshs19/insureme:latest
      source: pull

  - name: Run Docker container
    docker_container:
      name: insureme
      image: sapteshs19/insureme:latest
      state: started
      restart_policy: always
      ports:
        - "8080:8081"
